name: jshint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: apt
      run: sudo apt-get install -y nodejs npm

    - name: jshint install
      run: sudo npm i -g jshint

    - name: jshint run
      run: cd app/js && jshint
